version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./docker/frontend
    volumes:
      - .:/app:cached
    ports:
      - "5173:5173"
      - "24678:24678"
    tty: true
    environment:
      - VITE_USE_EMULATOR=true
    command: sh -c "npm install && npm run dev"
  firebase:
    container_name: firebase
    build: ./docker/firebase
    volumes:
      - ./.firebaserc:/opt/firebase/.firebaserc
      - ./firebase.json:/opt/firebase/firebase.json
      - ./firestore.rules.develop:/opt/firebase/firestore.rules
      - ./docker/firebase/bin/:/root/.cache:cached
      - ./docker/firebase/config/:/root/.config:cached
      - ./docker/firebase/src:/opt/firebase/
      - ./seed:/opt/firebase/seed
    ports:
      - 8080:8080
      - 5050:5050
      - 4000:4000
    tty: true
    working_dir: /opt/firebase
    command: firebase emulators:start --import=./seed

volumes:
  node_modules:

